version: "3.7"
services:
  spark-master:
    image: jupyter/pyspark-notebook:${SPARK_NOTEBOOK_VERSION}
    hostname: spark-master
    user: root
    ports:
      - "8080:8080"
      - "7077:7077"
      - "10000:10000"
    volumes:
      - .:/workspace
    working_dir: ${IMAGE_SPARK_HOME}
    environment:
      SPARK_LOCAL_IP: 0.0.0.0
      MASTER: spark://spark-master:7077
    command: ${IMAGE_SPARK_HOME}/bin/spark-class org.apache.spark.deploy.master.Master -h spark-master

  spark-worker-1:
    image: jupyter/pyspark-notebook:${SPARK_NOTEBOOK_VERSION}
    hostname: spark-worker-1
    user: root
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
      - "4040:4040"
    environment:
      SPARK_LOCAL_IP: spark-worker-1
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    volumes:
      - .:/workspace
    working_dir: ${IMAGE_SPARK_HOME}
    command: ${IMAGE_SPARK_HOME}/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077

  spark-worker-2:
    image: jupyter/pyspark-notebook:${SPARK_NOTEBOOK_VERSION}
    hostname: spark-worker-2
    user: root
    depends_on:
      - spark-master
    ports:
      - "8082:8082"
      - "4042:4040"
    environment:
      SPARK_LOCAL_IP: spark-worker-2
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 1G
      SPARK_WORKER_PORT: 8882
      SPARK_WORKER_WEBUI_PORT: 8082
    volumes:
      - .:/workspace
    working_dir: ${IMAGE_SPARK_HOME}
    command: ${IMAGE_SPARK_HOME}/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077


